<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PackageId>undercutf1</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <AssemblyName>undercutf1</AssemblyName>
    <ToolCommandName>undercutf1</ToolCommandName>
    <PackAsTool>true</PackAsTool>
    <IsPackable>true</IsPackable>
    <PackageTags>formula1;formula-1;f1;livetiming;timing;tui;terminal-ui</PackageTags>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <InvariantGlobalization>true</InvariantGlobalization>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <SelfContained>true</SelfContained>
    <PublishAot>true</PublishAot>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" />
    <PackageReference Include="InhibitSleep.Net" />
    <PackageReference Include="InMemoryLogger" />
    <PackageReference Include="LiveChartsCore" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="SharpWebview" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
    <PackageReference Include="SkiaSharp.NativeAssets.macOS" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="TextCopy" />
    <PackageReference Include="Vezel.Cathode" />
    <PackageReference Include="Vezel.Cathode.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference
      Include="../gen/UndercutF1.Console.SourceGeneration/UndercutF1.Console.SourceGeneration.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false"
      PrivateAssets="all"
    />
    <ProjectReference Include="..\UndercutF1.Data\UndercutF1.Data.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  <Target
    Name="OverrideVersion"
    AfterTargets="GetBuildVersion"
    Condition="'$(OverridePackageVersion)' != ''"
  >
    <PropertyGroup>
      <PackageVersion>$(OverridePackageVersion)</PackageVersion>
      <AssemblyVersion>$(OverridePackageVersion)</AssemblyVersion>
      <AssemblyInformationalVersion>$(OverridePackageVersion)</AssemblyInformationalVersion>
      <FileVersion>$(OverridePackageVersion)</FileVersion>
      <InformationalVersion>$(OverridePackageVersion)</InformationalVersion>
      <NugetPackageVersion>$(OverridePackageVersion)</NugetPackageVersion>
    </PropertyGroup>
  </Target>
</Project>
